export { default as Navbar } from './Navbar'
export { default as Features } from './Features'
export { default as Services } from './Services'
export { default as Purchase } from './Purchase'
export { default as Footer } from './Footer'